name       : lz4
version    : 1.8.1.2
release    : 10
source     :
    - https://github.com/lz4/lz4/archive/v1.8.1.2.tar.gz : 12f3a9e776a923275b2dc78ae138b4967ad6280863b77ff733028ce89b8123f9
license    :
    - BSD-2-Clause
    - GPL-2.0
component  : system.base
summary    : LZ4 commmand line tools
description: |
    LZ4 is a very fast lossless compression algorithm, providing compression speed at 400 MB/s per core, scalable with multi-cores CPU. It also features an extremely fast decoder, with speed in multiple GB/s per core, typically reaching RAM speed limits on multi-core systems.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
check      : |
    %make test
