name       : lz4
version    : 1.7.5
release    : 7
source     :
    - https://github.com/lz4/lz4/archive/v1.7.5.tar.gz : 0190cacd63022ccb86f44fa5041dc6c3804407ad61550ca21c382827319e7e7e
license    :
    - GPL-2.0
    - BSD-2-Clause
summary    : LZ4 commmand line tools
description: |
    LZ4 is a very fast lossless compression algorithm, providing compression speed at 400 MB/s per core, scalable with multi-cores CPU. It also features an extremely fast decoder, with speed in multiple GB/s per core, typically reaching RAM speed limits on multi-core systems.
component  : system.base
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
