name        : lz4
version     : 1.7.3
release     : 6
source     :
    - https://github.com/lz4/lz4/archive/v1.7.3.tar.gz : 6cc36e8971baf443dd66a334867402601efb55eec5ebde60d5c9021230cef1aa
license     :
    - GPL-2.0
    - BSD-2-Clause
summary     : LZ4 commmand line tools
description : |
    LZ4 is a very fast lossless compression algorithm, providing compression speed at 400 MB/s per core, scalable with multi-cores CPU. It also features an extremely fast decoder, with speed in multiple GB/s per core, typically reaching RAM speed limits on multi-core systems.
component: system.base
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
