name       : lz4
version    : 1.8.0
release    : 8
source     :
    - https://github.com/lz4/lz4/archive/v1.8.0.tar.gz : 2ca482ea7a9bb103603108b5a7510b7592b90158c151ff50a28f1ca8389fccf6
license    :
    - GPL-2.0
    - BSD-2-Clause
component  : system.base
summary    : LZ4 commmand line tools
description: |
    LZ4 is a very fast lossless compression algorithm, providing compression speed at 400 MB/s per core, scalable with multi-cores CPU. It also features an extremely fast decoder, with speed in multiple GB/s per core, typically reaching RAM speed limits on multi-core systems.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr LIBDIR=%libdir%
    rm -v $installdir/%libdir%/*.a
